"""Batch 006 : 15 images (11a7 a 12e2)."""
from insert_image import insert_image

BATCH = [
    {
        "filename": "11a70e33a14fa091d3a21a166921bcae.jpg",
        "image_type": "illustration",
        "subject_type": "object",
        "people_count": 0,
        "faces_visible": False,
        "description": "Illustration minimaliste sur fond noir : deux mains qui se font une promesse au petit doigt (pinky promise), petit coeur stylise au-dessus. Trait blanc fin, lineart epure. Format vertical type wallpaper.",
        "marketing_use": "Asset visuel doux et evocateur (promesse, engagement, complicite). Excellent pour tweets sur la confiance, les engagements tacites, 'on s'etait promis...'. Convient avatars 1 (Lucide), 4 (Romantique), 6 (Idealiste).",
        "emotions": ["tenderness", "intimacy", "promise", "nostalgia"],
        "ambiance": ["minimalist", "dark", "soft"],
        "setting": ["abstract"],
        "colors": ["black", "white", "monochrome"],
        "style_tags": ["illustration", "lineart", "wallpaper", "minimalist"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "vertical_wallpaper",
        "compaatible_fit": "medium",
        "suggested_avatars": [1, 2, 4, 6],
        "suggested_platforms": ["pinterest", "twitter_organic"],
        "usage_warning": "",
        "notes": "Tres versatile pour overlay texte.",
    },
    {
        "filename": "11bd3d4cc518514cfea26294eaa23d83.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple sud-asiatique (probablement pakistanais/indien) en uniforme militaire d'officier (homme, vert kaki, badge ASC, fourragere rouge) et femme en tenue ceremoniale avec dupatta bleue brodee d'or et casquette d'officier. Mur peint jaune/vert avec croissant de lune sculpte. Watermark 'nimbuwu'. Sourires.",
        "marketing_use": "Off-brand : marqueur culturel sud-asiatique fort + visages identifiables + watermark visible. Inutilisable directement.",
        "emotions": ["joy", "pride", "love"],
        "ambiance": ["formal", "ceremonial", "warm"],
        "setting": ["outdoor", "day"],
        "colors": ["green", "yellow", "blue"],
        "style_tags": ["lifestyle", "south_asian", "military", "has_watermark"],
        "cultural_specificity": "south_asian",
        "has_text_overlay": True,
        "quality_score": 4,
        "composition": "mid_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Watermark visible + marqueur culturel fort + visages identifiables.",
        "notes": "",
    },
    {
        "filename": "11c64a431301d9901618e2ceeb797d36.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple aesthetic sur un hors-bord au coucher de soleil. Elle (cheveux longs auburn, top noir, jupe verte, bracelets) tient un cocktail au pamplemousse, blottie contre lui (chemise blanche ouverte, lunettes de soleil rondes, montre, pantalon lin raye). Vagues qui ecument derriere, lumiere doree, mention 'featured' en filigrane.",
        "marketing_use": "Esthetique 'rich summer aesthetic' Pinterest/Instagram. Visuel beau mais luxe et visages tres identifiables. Convient eventuellement avatar 4 (Romantique) en metaphore 'le summer fling parfait' mais risque off-brand.",
        "emotions": ["luxury", "romance", "summer", "intimacy"],
        "ambiance": ["sunset", "golden_hour", "luxurious", "warm"],
        "setting": ["outdoor", "boat", "evening"],
        "colors": ["warm", "golden", "white"],
        "style_tags": ["lifestyle", "aesthetic", "luxury_lifestyle", "couple_aesthetic"],
        "cultural_specificity": "western_aesthetic",
        "has_text_overlay": True,
        "quality_score": 7,
        "composition": "mid_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [4],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "Visages identifiables + 'featured' watermark + univers luxe.",
        "notes": "",
    },
    {
        "filename": "11cb6fef54c44a303a6333624aae62f0.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Plan en contre-jour : deux mains qui se cherchent, doigts presque qui se touchent (s'accrochent par les petits doigts), silhouettes en ombre chinoise devant un coucher de soleil orange/violet sur l'ocean. Composition centrale parfaite.",
        "marketing_use": "Visuel emotionnel ULTRA fort pour Compaatible : 'connexion qui se cherche', 'l'instant juste avant'. Anonyme (que des mains), poetique. Excellent pour tous avatars sur le theme 'rencontre', 'attente', 'reconnaissance'.",
        "emotions": ["longing", "intimacy", "anticipation", "tenderness"],
        "ambiance": ["sunset", "golden_hour", "moody", "cinematic"],
        "setting": ["outdoor", "beach", "evening"],
        "colors": ["warm", "orange", "purple", "silhouette"],
        "style_tags": ["silhouette", "hands", "romantic", "minimalist"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 9,
        "composition": "close_up",
        "compaatible_fit": "high",
        "suggested_avatars": [1, 2, 3, 4, 6, 7, 9, 11],
        "suggested_platforms": ["pinterest", "instagram", "twitter_organic"],
        "usage_warning": "",
        "notes": "Top pick. Universel, anonyme, emotionnel.",
    },
    {
        "filename": "11ecfc0f9d1ba1bcb2a75b6d3878da9d.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Couple age (senior) sur deux balancoires cote a cote dans un parc au bord d'un lac. Lui (casquette noire, manteau noir) et elle (haut bleu/gris) en plein elan, jambes tendues, vue de profil/dos. Verdure, arbres, eau en arriere-plan. Photo style telephone, candide, vraie vie.",
        "marketing_use": "Asset PUISSANT pour Compaatible : 'amour qui dure', 'jouer encore a 60 ans', 'l'amour serieux ne se prend pas au serieux'. Anti-cliche, anti-jeunisme. Convient avatar 1 (Lucide), 6 (Idealiste), 9 (Separee), 11 (Parent solo). Tres rare dans le corpus.",
        "emotions": ["joy", "playfulness", "long_lasting_love", "tenderness"],
        "ambiance": ["candid", "natural", "warm", "wholesome"],
        "setting": ["outdoor", "park", "day"],
        "colors": ["green", "natural", "muted"],
        "style_tags": ["lifestyle", "candid", "senior_couple", "wholesome"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "wide_shot",
        "compaatible_fit": "high",
        "suggested_avatars": [1, 4, 6, 9, 11],
        "suggested_platforms": ["twitter_organic", "instagram", "pinterest"],
        "usage_warning": "",
        "notes": "Rare et precieux : couple age qui joue. Top pick.",
    },
    {
        "filename": "1205ef71309b25427ec40e8bd945d261.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple jeune sud-asiatique enlaces dans une rue indienne la nuit, etincelles de feu d'artifice/cierge derriere lui, guirlandes lumineuses dans les arbres. Elle (sari/lehenga vert pastel brode, bracelets) blottie contre lui (kurta sombre). Ambiance Diwali/festival.",
        "marketing_use": "Off-brand culturellement (festival indien tres marque) + visages identifiables. Inutilisable cible francaise.",
        "emotions": ["romance", "celebration", "intimacy"],
        "ambiance": ["nighttime", "festive", "warm"],
        "setting": ["outdoor", "street", "night"],
        "colors": ["warm", "green", "dark"],
        "style_tags": ["lifestyle", "south_asian", "festival", "candid"],
        "cultural_specificity": "south_asian",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "mid_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Marqueur culturel sud-asiatique tres fort + visages identifiables.",
        "notes": "",
    },
    {
        "filename": "123a15803929a17fa6ab9eb085c4824f.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple noir afro-americain sur le pont d'un voilier (pont en bois clair, voiles et cordages visibles). Lui (chemise blanche, gilet noir, montre) la tient blottie entre ses jambes, elle (robe blanche, foulard imprime sur les cheveux, alliance) regarde au loin pensive. Ambiance pre-mariage/engagement, photo pro mention '3/3'.",
        "marketing_use": "Visuel premium 'engagement aspirationnel'. Univers yacht/voilier (low fit Compaatible cote luxe) mais ton serein, complicite reelle. Convient avatar 4 (Romantique), 6 (Idealiste). Visages identifiables = vigilance droits.",
        "emotions": ["love", "calm", "intimacy", "aspiration"],
        "ambiance": ["warm", "serene", "premium"],
        "setting": ["outdoor", "boat", "day"],
        "colors": ["warm", "wood", "white"],
        "style_tags": ["lifestyle", "engagement_shoot", "premium", "yacht"],
        "cultural_specificity": "universal",
        "has_text_overlay": True,
        "quality_score": 7,
        "composition": "wide_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [4, 6],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "Mention '3/3' visible (carrousel Instagram) + visages identifiables.",
        "notes": "",
    },
    {
        "filename": "1244c968594721f4796942b6936bce94.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Plan cinematographique style period drama : un homme (chemise blanche, bretelles, profil) assis dans l'herbe haute face a une femme (corset blanc, jupe rouge corail) debout, dos a la camera, sous des branches couvertes de feuilles dorees. Lumiere chaude de fin d'apres-midi, tres pictoriale. Probable screenshot film.",
        "marketing_use": "Esthetique 'romance d'epoque' tres pinterest/feminine. Bon pour avatar 4 (Romantique), 6 (Idealiste) sur le theme 'l'amour intemporel'. Probable droits a verifier.",
        "emotions": ["romance", "longing", "wonder", "tension"],
        "ambiance": ["cinematic", "dreamy", "golden_hour", "warm"],
        "setting": ["outdoor", "nature", "day"],
        "colors": ["warm", "gold", "green", "red"],
        "style_tags": ["period_drama", "cinematic", "romantic", "tv_film_screenshot"],
        "cultural_specificity": "western_pop_culture",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "wide_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [4, 6],
        "suggested_platforms": ["pinterest", "instagram"],
        "usage_warning": "Probable screenshot film (a verifier).",
        "notes": "",
    },
    {
        "filename": "1248d3ae0123e821b9c57572884b8536.jpg",
        "image_type": "photo_real",
        "subject_type": "person",
        "people_count": 1,
        "faces_visible": False,
        "description": "Reflet dans un grand miroir ovale a cadre baroque blanc : femme en abaya noire et manche blanche, henne floral noir sur la main droite (qui tient son poignet gauche avec montre dorée et bague). Pochette en cuir rouge perlee a la main gauche. Branches de fleurs delicates a gauche et a droite. Sans visage.",
        "marketing_use": "Off-brand culturellement (abaya + henne = marqueur Moyen-Orient/Maghreb fort) + univers luxe accessoire. Inutilisable cible francaise.",
        "emotions": ["elegance", "intimacy", "mystery"],
        "ambiance": ["luxurious", "feminine", "minimalist"],
        "setting": ["indoor"],
        "colors": ["black", "white", "red"],
        "style_tags": ["lifestyle", "middle_eastern", "luxury_lifestyle", "feminine"],
        "cultural_specificity": "middle_eastern",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "close_up",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Marqueur culturel fort + univers luxe.",
        "notes": "",
    },
    {
        "filename": "124cb5ac576ba07d708f2cfcea9ec644.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple mixte (homme noir cheveux braids/locs courts, polo blanc / femme blanche cheveux blonds longs ondules, robe blanche dentelle, boucles d'oreilles dorees) face-a-face front contre front, sun flare etoile pile entre leurs deux nez. Pleine lumiere doree sur prairie en arriere-plan flou. Photo pro engagement-shoot.",
        "marketing_use": "Visuel EXTREMEMENT emotionnel : 'l'instant juste avant le baiser', 'la vraie connexion'. Sun flare = magie. Convient parfaitement avatar 4 (Romantique), 6 (Idealiste), 2 (Curieuse), 9 (Separee). MAIS : visages tres identifiables = vigilance droits/usage.",
        "emotions": ["love", "intimacy", "tenderness", "wonder"],
        "ambiance": ["golden_hour", "warm", "dreamy", "cinematic"],
        "setting": ["outdoor", "field", "evening"],
        "colors": ["warm", "golden", "white"],
        "style_tags": ["lifestyle", "engagement_shoot", "cinematic", "interracial"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 9,
        "composition": "close_up",
        "compaatible_fit": "high",
        "suggested_avatars": [2, 4, 6, 9],
        "suggested_platforms": ["pinterest", "instagram"],
        "usage_warning": "Visages identifiables (photo pro). Usage organique + creditation prudente.",
        "notes": "Top pick emotionnel.",
    },
    {
        "filename": "126b595951209c3473674e78a130a1a1.jpg",
        "image_type": "photo_real",
        "subject_type": "scene",
        "people_count": 0,
        "faces_visible": False,
        "description": "Coucher de soleil spectaculaire au-dessus d'un parc : ciel zebre de bandes rouges/roses et nuages bleu/gris en mouvement, allee de gravier qui serpente vers le fond, deux lampadaires allumes en silhouette, arbres et taillis en silhouette. Couleurs saturees, presque peinture.",
        "marketing_use": "Visuel d'ambiance puissant pour overlay texte. 'Le ciel est rouge ce soir'. Convient tous avatars sur themes contemplation, fin de journee, solitude/presence.",
        "emotions": ["wonder", "melancholy", "calm", "nostalgia"],
        "ambiance": ["sunset", "dramatic", "moody", "cinematic"],
        "setting": ["outdoor", "park", "evening"],
        "colors": ["red", "pink", "purple", "warm"],
        "style_tags": ["landscape", "sunset", "no_people", "dramatic"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "wide_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [1, 4, 7, 9, 11],
        "suggested_platforms": ["twitter_organic", "pinterest"],
        "usage_warning": "",
        "notes": "Excellent background pour overlay texte.",
    },
    {
        "filename": "1282984cae88995dd94fcc1d074a5c29.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Collage triptyque vertical d'un meme couple sud-asiatique sur plage indienne au coucher de soleil brumeux : 1) etreinte de cote, soleil sur l'horizon ; 2) il la fait tourner sous son bras (mouvement de danse) ; 3) de dos main dans la main face a la mer. Lumiere argentee/doree, sable mouille reflechissant. Silhouettes principalement.",
        "marketing_use": "Asset puissant 'connexion vraie' : moments candides, sequence narrative, silhouettes (visages peu lisibles). Plage indienne mais lecture universelle possible. Convient avatars 1, 2, 4, 6, 9. Bon pour storytelling 'l'evolution d'un moment'.",
        "emotions": ["love", "joy", "intimacy", "playfulness"],
        "ambiance": ["sunset", "golden_hour", "candid", "warm"],
        "setting": ["outdoor", "beach", "evening"],
        "colors": ["warm", "silver", "golden", "muted"],
        "style_tags": ["lifestyle", "candid", "collage", "sequence"],
        "cultural_specificity": "south_asian",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "collage",
        "compaatible_fit": "medium",
        "suggested_avatars": [1, 2, 4, 6, 9],
        "suggested_platforms": ["instagram", "pinterest"],
        "usage_warning": "Couple identifiable (mais flou/silhouettes). Marqueur culturel modere (lecture universelle possible).",
        "notes": "Storytelling sequence.",
    },
    {
        "filename": "12db3af232c750936ddfc663a0e2afc4.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple jeune en tenue de soiree (elle, robe noire moulante a sequins, brune longs cheveux / lui, costume sombre, chemise blanche ouverte) s'embrassant intensement debout devant une rangee de voitures de sport (Ferrari rouge, Lamborghini blanche) garees sous un porche d'hotel/casino. Ambiance Monaco/Cannes nightlife.",
        "marketing_use": "Off-brand total : symboles de luxe ostentatoire (Ferrari, Lambo), nightlife rich kids. Oppose au positionnement Compaatible (compatibilite > apparence).",
        "emotions": ["passion", "luxury", "excitement"],
        "ambiance": ["nighttime", "luxurious", "intense"],
        "setting": ["outdoor", "urban", "night"],
        "colors": ["dark", "red", "white"],
        "style_tags": ["lifestyle", "luxury_lifestyle", "supercar", "couple_aesthetic"],
        "cultural_specificity": "western_aesthetic",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "mid_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Off-brand : luxe ostentatoire (supercars). Visages identifiables.",
        "notes": "",
    },
    {
        "filename": "12e16c22dd61ef853a7f7e77a75559ed.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Selfie miroir en salle de sport, couple jeune athletique s'embrasse. Elle (brassiere blanche, short noir, Nike blanches, jambe levee en l'air vers lui), lui (t-shirt noir, short noir, casquette grise) tient le telephone. Machines de musculation rouges/noires autour, gourde rouge, lumiere chaude tamisee.",
        "marketing_use": "Esthetique 'gym couple' Instagram. Univers fitness aspirationnel mais ton 'on s'amuse', faces partiellement obscurcies (lui derriere telephone). Convient avatar 4 (Romantique), 6 (Idealiste) sur theme 'complicite quotidienne'. Risque cliche 'couple-goal performatif'.",
        "emotions": ["love", "playfulness", "intimacy", "fitness"],
        "ambiance": ["intimate", "warm", "indoor"],
        "setting": ["indoor", "gym", "evening"],
        "colors": ["warm", "dark", "red"],
        "style_tags": ["lifestyle", "fitness", "gym_couple", "selfie", "couple_aesthetic"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "mid_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [4, 6],
        "suggested_platforms": ["instagram", "pinterest"],
        "usage_warning": "Visages partiellement visibles (telephone devant). Esthetique 'gym couple' tres cliche IG.",
        "notes": "",
    },
    {
        "filename": "12e2b49b4abe1050ebf1977176754192.jpg",
        "image_type": "ai_generated",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Couple en silhouette marchant main dans la main sur plage humide au coucher de soleil, soleil pile entre leurs deux silhouettes au centre, reflet long et brillant dans le sable mouille au premier plan. Elle (robe blanche fluide, cheveux longs), lui (chemise blanche). Composition tres symetrique, esthetique IA detectable.",
        "marketing_use": "Visuel emotionnel doux 'avancer ensemble'. Symetrie trop parfaite (IA), Pinterest-friendly. Convient avatar 4 (Romantique), 6 (Idealiste), 9 (Separee) sur theme 'l'apres', 'recommencer ensemble'. Eviter Twitter (vibes IA visibles).",
        "emotions": ["romance", "calm", "hope", "intimacy"],
        "ambiance": ["sunset", "golden_hour", "dreamy", "cinematic"],
        "setting": ["outdoor", "beach", "evening"],
        "colors": ["warm", "orange", "silhouette"],
        "style_tags": ["ai_generated", "silhouette", "romantic", "symmetrical"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "wide_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [4, 6, 9],
        "suggested_platforms": ["pinterest", "instagram"],
        "usage_warning": "IA detectable. Eviter Twitter.",
        "notes": "",
    },
]


def main():
    inserted = 0
    skipped = 0
    for item in BATCH:
        try:
            res = insert_image(item)
            if res:
                inserted += 1
            else:
                skipped += 1
        except Exception as e:
            print(f"ERROR {item['filename']}: {e}")
            skipped += 1
    print(f"\nBatch 006 : {inserted} inserees, {skipped} skipped.")


if __name__ == "__main__":
    main()
