"""Batch 005 : 15 images (03e2 a 0513)."""
from insert_image import insert_image

BATCH = [
    {
        "filename": "03e27ccddc25a01f9a424633e33b15af.jpg",
        "image_type": "photo_real",
        "subject_type": "object",
        "people_count": 0,
        "faces_visible": False,
        "description": "Pont d'un yacht de luxe la nuit, plancher en teck eclaire, spots au plafond, feu d'artifice flou au loin sur l'horizon urbain. Bande rouge lumineuse en bas a gauche. Vide humain.",
        "marketing_use": "Univers yacht/luxe : off-brand pour Compaatible (positionnement realiste et 'compatibilite > apparence'). N'evoque pas la connexion humaine.",
        "emotions": ["loneliness", "luxury", "anticipation"],
        "ambiance": ["nighttime", "cinematic", "moody"],
        "setting": ["outdoor", "yacht", "night"],
        "colors": ["dark", "warm_accents", "red"],
        "style_tags": ["luxury_lifestyle", "yacht", "no_people"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "wide_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Off-brand : luxe ostentatoire.",
        "notes": "",
    },
    {
        "filename": "03e68a727127c137de08a29c64c28c38.jpg",
        "image_type": "photo_real",
        "subject_type": "scene",
        "people_count": 1,
        "faces_visible": False,
        "description": "Pont arriere d'un mega-yacht au coucher de soleil orange. Table dressee elegante au premier plan (verres, bougie, serviettes), salon avec canapes blancs, une silhouette de femme en robe longue au fond. Ciel embrase.",
        "marketing_use": "Imagerie 'rich girl summer' : off-brand pour Compaatible.",
        "emotions": ["luxury", "anticipation", "aspiration"],
        "ambiance": ["sunset", "warm", "luxurious"],
        "setting": ["outdoor", "yacht", "evening"],
        "colors": ["warm", "orange", "white"],
        "style_tags": ["luxury_lifestyle", "yacht"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "wide_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Off-brand : tout dans le decor luxe, rien dans la connexion.",
        "notes": "",
    },
    {
        "filename": "03f18eefe48bdbb139e4fd17eff4a8e0.jpg",
        "image_type": "photo_real",
        "subject_type": "object",
        "people_count": 0,
        "faces_visible": False,
        "description": "Port de peche la nuit. Bateaux de peche aux mats hauts amarres, reflets de lumieres jaunes/blanches dans l'eau noire. Proue d'un grand bateau a droite avec le mot 'ANN' partiellement visible. Atmosphere brute et nocturne.",
        "marketing_use": "Visuel d'ambiance solitaire/contemplative, port nocturne. Peu de lien direct avec le dating ; usage possible pour avatar 7 (Solitaire) sur le theme 'attendre que ca arrive sans rien faire'.",
        "emotions": ["solitude", "calm", "contemplation"],
        "ambiance": ["nighttime", "moody", "industrial"],
        "setting": ["outdoor", "harbor", "night"],
        "colors": ["dark", "yellow_lights", "muted"],
        "style_tags": ["documentary", "no_people", "nightscape"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "wide_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [7],
        "suggested_platforms": ["twitter_organic"],
        "usage_warning": "",
        "notes": "",
    },
    {
        "filename": "04081a9293bfed208f286286050438f4.jpg",
        "image_type": "ai_generated",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Silhouettes d'un couple jeune face a face au coucher de soleil sur la plage, soleil oran flamboyant pile entre leurs deux visages. Elle (longue robe blanche, cheveux longs) bras autour de son cou, lui (chemise blanche) main sur sa taille. Image hyper romantique, esthetique IA.",
        "marketing_use": "Visuel emotionnel fort 'l'instant ou tout colle'. Bon pour la promesse Compaatible (vraie connexion). Detectable IA (proportions trop parfaites, lighting trop dramatique).",
        "emotions": ["romance", "intimacy", "passion"],
        "ambiance": ["sunset", "golden_hour", "cinematic"],
        "setting": ["outdoor", "beach", "evening"],
        "colors": ["warm", "orange", "silhouette"],
        "style_tags": ["ai_generated", "silhouette", "romantic"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "mid_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [1, 2, 4, 9],
        "suggested_platforms": ["pinterest", "instagram"],
        "usage_warning": "IA detectable. Eviter Twitter (vibes 'fake').",
        "notes": "",
    },
    {
        "filename": "0417404386fcda647a0d28fbdd793a4e.jpg",
        "image_type": "photo_real",
        "subject_type": "scene",
        "people_count": 0,
        "faces_visible": False,
        "description": "Terrasse d'un bungalow sur pilotis (Maldives/Polynesie) la nuit. Deux transats avec serviettes roulees, lanterne allumee, eau turquoise eclairee, autres bungalows au loin. Parasol blanc en hauteur.",
        "marketing_use": "Univers honeymoon/voyage en couple. Off-brand direct (luxe), mais utilisable en metaphore 'la place a cote de toi reste vide'.",
        "emotions": ["calm", "intimacy", "longing"],
        "ambiance": ["nighttime", "tropical", "luxurious"],
        "setting": ["outdoor", "overwater", "night"],
        "colors": ["dark", "turquoise", "warm_lights"],
        "style_tags": ["travel", "luxury_lifestyle", "no_people"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "wide_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [7, 9],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "",
        "notes": "",
    },
    {
        "filename": "044bc9fbf6a62f2630c09c39c75eadb4.jpg",
        "image_type": "ai_generated",
        "subject_type": "group",
        "people_count": 12,
        "faces_visible": True,
        "description": "Pont d'un yacht en mode soiree, eclairages neon roses/violets/verts, un DJ/homme en blanc surplombe la scene depuis l'etage, foule de jeunes en tenue de soiree autour d'un bar circulaire lumineux, ciel etoile. Vibes 'rich party night'. IA evidente (proportions, eclairages).",
        "marketing_use": "Off-brand total. Univers fete superficielle, opposition exacte au positionnement Compaatible.",
        "emotions": ["excitement", "luxury", "superficial"],
        "ambiance": ["nighttime", "party", "neon"],
        "setting": ["outdoor", "yacht", "night"],
        "colors": ["neon", "purple", "pink"],
        "style_tags": ["ai_generated", "party", "yacht"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 4,
        "composition": "wide_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Off-brand + IA visible.",
        "notes": "",
    },
    {
        "filename": "045fd9bca3a8cf7ee974deba9e371844.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "POV selfie dans cabine business class d'avion, jeune couple americain (homme cheveux chatains, t-shirt blanc / femme blonde, top blanc, montre Apple) qui s'embrasse en cachant les visages derriere deux passeports americains tenus en eventail.",
        "marketing_use": "Image 'couple-goal travel' archi-virale Instagram/Pinterest. Convient avatar 2 (Curieuse), 4 (Romantique) pour la promesse 'partir a deux'. Suggere succes du couple.",
        "emotions": ["love", "adventure", "excitement"],
        "ambiance": ["travel", "intimate", "casual"],
        "setting": ["indoor", "airplane", "day"],
        "colors": ["neutral", "blue_passports", "soft"],
        "style_tags": ["lifestyle", "travel", "couple_goals", "selfie"],
        "cultural_specificity": "us_americana",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "close_up",
        "compaatible_fit": "high",
        "suggested_avatars": [2, 4, 9],
        "suggested_platforms": ["pinterest", "instagram", "twitter_organic"],
        "usage_warning": "Visages caches : OK droits image.",
        "notes": "",
    },
    {
        "filename": "04718e2df5ab6a7d0ba1a25e7e424ad9.jpg",
        "image_type": "illustration",
        "subject_type": "object",
        "people_count": 0,
        "faces_visible": False,
        "description": "Illustration peinture rose pastel : deux coeurs entrelaces (un evide rouge, un plein rose) avec inscription manuscrite partielle 'I'm ok' a droite. Texture papier granuleux. Format vertical type wallpaper.",
        "marketing_use": "Asset visuel doux/feminin. Texte 'I'm ok' interessant pour avatar 9 (Separee) ou 1 (Lucide) sur le ton 'fake-ok'. Mais texte preexistant pourrait gener.",
        "emotions": ["bittersweet", "tenderness", "vulnerability"],
        "ambiance": ["soft", "feminine", "minimalist"],
        "setting": ["abstract"],
        "colors": ["pink", "pastel", "rose"],
        "style_tags": ["illustration", "wallpaper", "feminine", "has_text"],
        "cultural_specificity": "universal",
        "has_text_overlay": True,
        "quality_score": 6,
        "composition": "vertical_wallpaper",
        "compaatible_fit": "low",
        "suggested_avatars": [1, 9],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "Texte preexistant 'I'm ok' partiellement coupe.",
        "notes": "",
    },
    {
        "filename": "04922b6b19a8455a058c4b1a518548bd.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Couple sud-asiatique (probablement pakistanais/indien) en tenue noire elegante allonge dans l'herbe, jonche de petales de roses rouges et roses. Homme penche sur la femme qui tient des roses rouges devant son visage, lui tend une fleur blanche. Bracelets noirs, henne sur les mains.",
        "marketing_use": "Tres beau visuel romantique mais culturellement marque (mariage/engagement sud-asiatique). Hors cible francaise principale Compaatible.",
        "emotions": ["romance", "tenderness", "intimacy"],
        "ambiance": ["dreamy", "warm", "soft"],
        "setting": ["outdoor", "park", "day"],
        "colors": ["red", "black", "green"],
        "style_tags": ["lifestyle", "romantic", "south_asian"],
        "cultural_specificity": "south_asian",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "close_up",
        "compaatible_fit": "low",
        "suggested_avatars": [4],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "Visages identifiables + marqueur culturel fort.",
        "notes": "",
    },
    {
        "filename": "04a355981288bf32e019ec7005964672.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": True,
        "description": "Photo vintage colorisee, couple bollywood/indien classique assis sur un pont en bambou en pleine nature, sous un arbre. Elle (sari et bindi) sourit a l'objectif, lui (chemise grise) regarde au loin pensif. Lumiere douce, ambiance romantique nostalgique.",
        "marketing_use": "Photo de film bollywood vintage (annees 50/60). Off-brand culturellement et droits image incertains.",
        "emotions": ["nostalgia", "romance", "calm"],
        "ambiance": ["vintage", "soft", "nature"],
        "setting": ["outdoor", "nature", "day"],
        "colors": ["muted", "warm", "vintage"],
        "style_tags": ["vintage", "bollywood", "tv_film_screenshot"],
        "cultural_specificity": "south_asian",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "mid_shot",
        "compaatible_fit": "off_brand",
        "suggested_avatars": [],
        "suggested_platforms": [],
        "usage_warning": "Probable screenshot film bollywood vintage. Droits + culture hors cible.",
        "notes": "",
    },
    {
        "filename": "04c36197cc8b87229a779bb6eda4eb8d.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Plan cinematographique : couple se tenant la main devant un grand manoir en pierre crepusculaire. Elle en longue robe grise/argentee fluide, lui en costume sombre. Cadrage 'Pride & Prejudice' / Bridgerton-vibes. Lumiere de fin de journee, grand arbre a droite.",
        "marketing_use": "Esthetique 'period drama' tres feminine, ideale pinterest. Convient avatar 4 (Romantique) sur la promesse 'le grand amour qui existe vraiment'. Probable screenshot film a verifier.",
        "emotions": ["romance", "longing", "wonder"],
        "ambiance": ["cinematic", "dreamy", "twilight"],
        "setting": ["outdoor", "estate", "evening"],
        "colors": ["muted", "green", "grey"],
        "style_tags": ["period_drama", "cinematic", "romantic"],
        "cultural_specificity": "western_pop_culture",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "wide_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [4, 9],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "Probable screenshot film (Pride & Prejudice ?). Usage organique + creditation prudente.",
        "notes": "",
    },
    {
        "filename": "04d98cff6b1e6323f5d3275ee6940980.jpg",
        "image_type": "photo_real",
        "subject_type": "scene",
        "people_count": 0,
        "faces_visible": False,
        "description": "Coucher de soleil sur la mer : grand soleil orange/rouge a moitie noye sous l'horizon, ciel strie de nuages oranges et roses, ocean calme reflechissant la lumiere, mince ligne de cote a l'horizon.",
        "marketing_use": "Visuel d'ambiance classique. Utile en arriere-plan de tweet/post avec citation/copy. Convient tous avatars.",
        "emotions": ["calm", "wonder", "nostalgia"],
        "ambiance": ["sunset", "warm", "peaceful"],
        "setting": ["outdoor", "beach", "evening"],
        "colors": ["orange", "red", "warm"],
        "style_tags": ["nature", "landscape", "no_people"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 7,
        "composition": "wide_shot",
        "compaatible_fit": "low",
        "suggested_avatars": [1, 4, 7, 9],
        "suggested_platforms": ["twitter_organic", "pinterest"],
        "usage_warning": "",
        "notes": "Bon background pour overlay texte.",
    },
    {
        "filename": "05088b68d76f1daa90babf7421cd692d.png",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Plan cinematographique de dos : jeune femme (cheveux mi-longs bruns) et jeune homme (cheveux bruns) cote a cote, en manteaux sombres, regardent l'ocean gris-vert. Atmosphere melancolique, palette tres desaturee, vibes film coreen/europeen.",
        "marketing_use": "Excellent visuel pour avatar 1 (Lucide), 7 (Solitaire), 9 (Separee) : 'silence partage qui dit tout' / 'rester sans rien dire'. Suggere intimite calme et reflexion. Cohere avec ton Compaatible.",
        "emotions": ["melancholy", "intimacy", "contemplation"],
        "ambiance": ["cinematic", "moody", "overcast"],
        "setting": ["outdoor", "coast", "day"],
        "colors": ["muted", "grey", "green"],
        "style_tags": ["cinematic", "back_view", "moody"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 8,
        "composition": "mid_shot",
        "compaatible_fit": "high",
        "suggested_avatars": [1, 4, 7, 9],
        "suggested_platforms": ["twitter_organic", "pinterest", "instagram"],
        "usage_warning": "Probable screenshot film (a verifier).",
        "notes": "",
    },
    {
        "filename": "0513a4d31ae58e841087c2a0f506a7dc.jpg",
        "image_type": "ai_generated",
        "subject_type": "object",
        "people_count": 0,
        "faces_visible": False,
        "description": "Table dressee pour deux sur terrasse de rooftop au crepuscule, deux verres a vin, bougies allumees, petit bouquet de fleurs orange, vue panoramique sur skyline urbain illumine en arriere-plan flou.",
        "marketing_use": "Visuel 'date romantique parfaite' tres pinterest/IA. Utile avatar 4 (Romantique) ; bon en metaphore 'la place vide en face'. IA detectable.",
        "emotions": ["anticipation", "romance", "luxury"],
        "ambiance": ["evening", "warm", "cinematic"],
        "setting": ["outdoor", "rooftop", "evening"],
        "colors": ["warm", "orange", "urban_lights"],
        "style_tags": ["ai_generated", "date_night", "no_people"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 6,
        "composition": "mid_shot",
        "compaatible_fit": "medium",
        "suggested_avatars": [2, 4, 9],
        "suggested_platforms": ["pinterest"],
        "usage_warning": "IA detectable.",
        "notes": "",
    },
    {
        "filename": "04a73f291332f300ec5af3a08eeea97a.jpg",
        "image_type": "photo_real",
        "subject_type": "couple",
        "people_count": 2,
        "faces_visible": False,
        "description": "Couple jeune dansant/jouant sous la pluie dans une rue desertee en fin de journee. Elle (t-shirt blanc, jean noir) se laisse tourner par lui (chemise sombre trempee), bras en l'air. Sol mouille reflete, arbres et cables electriques en silhouette, ciel sepia/grain photo argentique vintage.",
        "marketing_use": "Asset emotionnel TRES fort 'spontaneite vraie d'un couple' : l'inverse du 'date Instagram'. Convient parfaitement avatar 1 (Lucide), 2 (Curieuse), 9 (Separee) sur le theme 'on s'est trouves dans la vraie vie, pas dans une appli a swipe'. Visages caches/lointain = OK droits.",
        "emotions": ["joy", "spontaneity", "intimacy", "freedom"],
        "ambiance": ["moody", "rainy", "vintage", "cinematic"],
        "setting": ["outdoor", "street", "evening"],
        "colors": ["sepia", "warm", "muted"],
        "style_tags": ["lifestyle", "grainy", "vintage_filter", "couple_dance"],
        "cultural_specificity": "universal",
        "has_text_overlay": False,
        "quality_score": 9,
        "composition": "wide_shot",
        "compaatible_fit": "high",
        "suggested_avatars": [1, 2, 4, 9],
        "suggested_platforms": ["pinterest", "instagram", "twitter_organic"],
        "usage_warning": "",
        "notes": "Top pick du batch.",
    },
]


def main():
    inserted = 0
    skipped = 0
    for item in BATCH:
        try:
            res = insert_image(item)
            if res:
                inserted += 1
            else:
                skipped += 1
        except Exception as e:
            print(f"ERROR {item['filename']}: {e}")
            skipped += 1
    print(f"\nBatch 005 : {inserted} inserees, {skipped} skipped.")


if __name__ == "__main__":
    main()
